---
image_pull_secrets:
- DOCKER_REGISTRY_AUTHENTICATION_JSON
kind: pipeline
name: Main CI pipeline
steps:
- environment:
    CACHE_ENABLED: ${CACHE_ENABLED:-true}
    CACHE_EXTRA_DIRS: ${CACHE_EXTRA_DIRS:-["/root/.cargo","/root/.npm","/root/.rustup",".blaze/cache",".blaze/repositories",".blaze/rust"]}
    CACHE_KEY: ${CACHE_KEY:-ci-${DRONE_BRANCH}}
    CACHE_STORAGE: ${CACHE_STORAGE:-/tmp/cache}
    DOCKER_REGISTRY_PASSWORD:
      from_secret: DOCKER_REGISTRY_PASSWORD
    DOCKER_REGISTRY_USERNAME:
      from_secret: DOCKER_REGISTRY_USERNAME
    PARALLELISM: ${PARALLELISM:-2}
    ROOT: ${ROOT:-/drone/src}
    SELECTOR: ${SELECTOR:-"All"}
    TARGETS: ${TARGETS:-ci-setup,ci-build,ci-test,ci-teardown}
    VARIABLES: ${VARIABLES:-{"lint":{"fix":false}}}
  image: registry.rnzaou.me/ci:latest
  name: ci
  pull: true
  volumes:
  - name: cache
    path: /tmp/cache
  - name: docker-socket
    path: /var/run/docker.sock
  - name: blaze-builds
    path: /var/lib/blaze/builds
  - name: ssh
    path: /root/.ssh
type: docker
volumes:
- host:
    path: /var/lib/drone/.ssh
  name: ssh
- host:
    path: /var/lib/cache
  name: cache
- host:
    path: /var/lib/blaze/builds
  name: blaze-builds
- host:
    path: /run/user/1002/docker.sock
  name: docker-socket
workspace:
  path: /drone/src
---
kind: signature
hmac: 9b30fe3c2e6f209014dd0cf5ed10579b2fd9fd457a898b5a53d61e38cb0f75b9

...
