---
image_pull_secrets:
- DOCKER_REGISTRY_AUTHENTICATION_JSON
kind: pipeline
name: Main CI pipeline
steps:
- environment:
    CACHE_ENABLED: ${CACHE_ENABLED:-true}
    CACHE_EXTRA_DIRS: /root/.cargo,/root/.npm,/root/.rustup,.blaze/cache,.blaze/repositories,.blaze/rust
    CACHE_IGNORE_EXISTING: ${CACHE_IGNORE_EXISTING:-false}
    CACHE_KEY: ci-${DRONE_BRANCH}
    CACHE_STORAGE: /var/lib/cache
    DOCKER_REGISTRY_PASSWORD:
      from_secret: DOCKER_REGISTRY_PASSWORD
    DOCKER_REGISTRY_USERNAME:
      from_secret: DOCKER_REGISTRY_USERNAME
  image: registry.rnzaou.me/ci:latest
  name: ci
  pull: true
  volumes:
  - name: cache
    path: /var/lib/cache
  - name: docker-socket
    path: /var/run/docker.sock
  - name: blaze-builds
    path: /var/lib/blaze/builds
  - name: ssh
    path: /root/.ssh
type: docker
volumes:
- host:
    path: /var/lib/drone/.ssh
  name: ssh
- host:
    path: /var/lib/cache
  name: cache
- host:
    path: /var/lib/blaze/builds
  name: blaze-builds
- host:
    path: /run/user/1002/docker.sock
  name: docker-socket
workspace:
  path: /drone/src
---
kind: signature
hmac: 32a3e5a4688ff3031e590535dab4876a5ba68e464de74500c3d46581e07f8ae9

...
