[package]
name = "ci"
version = "0.1.0"
edition = "2021"

[dependencies]
blaze-core = { version = "0.2.10" }
possibly = "1"
serde = "1.0"
serde_json = "1.0"
anyhow = "1.0"
tar = "0.4"
flate2 = "1.0"
fs4 = "0.8"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1